const privilages = [
  { name: "Create a poll", active: true },
  { name: "Delete a poll", active: true },
  { name: "Edit a poll", active: true },
  { name: "Hide a poll", active: true },
  { name: "Closing a poll", active: true },
  { name: "Message users", active: true },
  { name: "Create new topic", active: true },
  { name: "Create a subtopic", active: true },
  { name: "Approve new subtopics", active: true },
  { name: "Delete new subtopics", active: true },
  { name: "Edit user access", active: true },
  { name: "Delete users", active: true },
  { name: "Delete photos", active: true },
  { name: "Edit photos", active: true },
  { name: "Add internal users", active: true },
  { name: "Edit internal users", active: true },
  { name: "Delete internal users", active: true },
  { name: "Flag polls", active: true },
  { name: "Add answers", active: true },
  { name: "Edit answers", active: true },
  { name: "Hide answers", active: true },
  { name: "Delete answers", active: true },
  { name: "Like", active: true },
  { name: "Dislike", active: true },
  { name: "Hide chat message", active: true },
  { name: "Delete chat message", active: true },
  { name: "Add internal permission types", active: true },
  { name: "Edit internal permissions", active: true },
  { name: "Delete internal permissions", active: true },
  { name: "Add internal roles", active: true },
  { name: "Edit internal roles", active: true },
  { name: "Delete internal roles", active: true },
  { name: "Create settings", active: true },
  { name: "Edit settings", active: true },
  { name: "Delete settings", active: true },
];

export default privilages;
