version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./flask_app/Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:5000"
    environment:
      - APP_ENV=${APP_ENV}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'if [ "$APP_ENV" = "development"]; then curl -f http://localhost:5000/health || exit 1; else curl -f https://ai.poldit.com/health || exit 1; fi',
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    # volumes:
    #   - ./flask_app:/app

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    # build: ./worker
    env_file:
      - .env
  #   volumes:
  #     - ./worker:/worker
